//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapConsumeEksame.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Catch", Namespace="http://schemas.datacontract.org/2004/07/SoapServiceEksamensTest")]
    [System.SerializableAttribute()]
    public partial class Catch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string artField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string navnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ugeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string art {
            get {
                return this.artField;
            }
            set {
                if ((object.ReferenceEquals(this.artField, value) != true)) {
                    this.artField = value;
                    this.RaisePropertyChanged("art");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                if ((object.ReferenceEquals(this.navnField, value) != true)) {
                    this.navnField = value;
                    this.RaisePropertyChanged("navn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uge {
            get {
                return this.ugeField;
            }
            set {
                if ((this.ugeField.Equals(value) != true)) {
                    this.ugeField = value;
                    this.RaisePropertyChanged("uge");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/SoapServiceEksamensTest")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCatches", ReplyAction="http://tempuri.org/IService1/GetCatchesResponse")]
        SoapConsumeEksame.ServiceReference1.Catch[] GetCatches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCatches", ReplyAction="http://tempuri.org/IService1/GetCatchesResponse")]
        System.Threading.Tasks.Task<SoapConsumeEksame.ServiceReference1.Catch[]> GetCatchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCatchById", ReplyAction="http://tempuri.org/IService1/GetCatchByIdResponse")]
        SoapConsumeEksame.ServiceReference1.Catch GetCatchById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCatchById", ReplyAction="http://tempuri.org/IService1/GetCatchByIdResponse")]
        System.Threading.Tasks.Task<SoapConsumeEksame.ServiceReference1.Catch> GetCatchByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCatch", ReplyAction="http://tempuri.org/IService1/AddCatchResponse")]
        int AddCatch(string navn, string art, int uge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCatch", ReplyAction="http://tempuri.org/IService1/AddCatchResponse")]
        System.Threading.Tasks.Task<int> AddCatchAsync(string navn, string art, int uge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        SoapConsumeEksame.ServiceReference1.CompositeType GetDataUsingDataContract(SoapConsumeEksame.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SoapConsumeEksame.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(SoapConsumeEksame.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SoapConsumeEksame.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SoapConsumeEksame.ServiceReference1.IService1>, SoapConsumeEksame.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SoapConsumeEksame.ServiceReference1.Catch[] GetCatches() {
            return base.Channel.GetCatches();
        }
        
        public System.Threading.Tasks.Task<SoapConsumeEksame.ServiceReference1.Catch[]> GetCatchesAsync() {
            return base.Channel.GetCatchesAsync();
        }
        
        public SoapConsumeEksame.ServiceReference1.Catch GetCatchById(int id) {
            return base.Channel.GetCatchById(id);
        }
        
        public System.Threading.Tasks.Task<SoapConsumeEksame.ServiceReference1.Catch> GetCatchByIdAsync(int id) {
            return base.Channel.GetCatchByIdAsync(id);
        }
        
        public int AddCatch(string navn, string art, int uge) {
            return base.Channel.AddCatch(navn, art, uge);
        }
        
        public System.Threading.Tasks.Task<int> AddCatchAsync(string navn, string art, int uge) {
            return base.Channel.AddCatchAsync(navn, art, uge);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public SoapConsumeEksame.ServiceReference1.CompositeType GetDataUsingDataContract(SoapConsumeEksame.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<SoapConsumeEksame.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(SoapConsumeEksame.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
